services:
  dyndns_proxy_im:
    container_name: dyndns_proxy
    build: .
    image: m0litz/dyndns_proxy_im
    ports:
#      - "5000:80"
      - "5001:443"
    volumes:
      - ./proxy_files/:/var/APP/:z
    environment:
      - CONFIG_PATH=/var/APP/proxy.conf
      - LOG_PATH=/var/APP/dyndnsproxy.log
    restart: on-failure